<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SixJars.Infrastructure\SixJars.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Shared\**\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
